### ISSUE TITLE
Deadlock during disconnect of Modbus RTU Client (SerialPort)

### ISSUE THREAD

**Issue by Gonzo4** [rossmann-engineering/EasyModbusTCP.NET#1]
Hallo,

beim Aufruf der Disconnect Methode beim Modbus-Client kommt es bei mir öfters zu einem Deadlock, genauer gesagt bei serialport.Close(). Hierbei hängt ein weiterer Thread immer in der DataReceivedHandler-Methode in der while-Schleife in Zeile 429 fest, da die Variable dataReceived noch true ist.

            while (receiveActive | dataReceived)
        		System.Threading.Thread.Sleep(10);

Hinweis: Der Aufruf der ModbusClient-Methoden kann bei mir immer aus einem anderen Thread erfolgen, jedoch sind diese alle threadsafe gegen gleichzeiten Aufruf abgesichert.

Evtl. muss man vor dem Aufruf von serialport.Close() das DataReceived-Event erst sicher beenden?!

Dennoch klasse Arbeit, Danke soweit ;)

**Comment by rossmann-engineering** [comment]
Vielen Dank für den Hinweis! Ich werde dem nachgehen.

Grüße
Stefan
