### ISSUE TITLE
Is this a legit library

### ISSUE THREAD

**Issue by Zapnologica** [rossmann-engineering/EasyModbusTCP.NET#116]
Good day,

I just wanted to ask if this is a legit and relevant library to use?

Everything seems to be written in one class?
Almost 3000 lines of code in this one file?
No Interfaces or any software design patterns used?

**Comment by gbellini79** [comment]
It depends: do you need something that just works or a library that is also beautiful, easily extensible and thoroughly documented?
We fall in the former category and have used it in several project without issues.

**Comment by Padanian** [comment]
A single file is much better to mantain that a plethora of useless overhead files. And as @gbellini79 said, it works a charme.
Other than that, what does your message have anything to do with anything?

**Comment by Zapnologica** [comment]
So I am not here to throw stones at anyone, or get into a one file vs many file discussion.  It was a genuine question to see if this library is still being supported and maintained and improved.

I come from a software engineering background where file structures, code re-useability, extendability, testability etc are all very important factors to consider before bringing in a library which will need to be maintained and used by many other developers who also follow those coding standards.

I would argue that 3000 lines of code in one file is the complete opposite of easy to maintain.  But let's not get into that.

I assume this code has been ported or orginated from a C or embedded background?

I will test its functionality out as you guys say it works well, and then see if we can maybe adapt it to use some of our coding standards.

Thank you for you replies.
