### ISSUE TITLE
Holding register above 40100 gives error. 

### ISSUE THREAD

**Issue by Rahul828086** [rossmann-engineering/EasyModbusTCP.NET#15]
Hello, I am using easy modbus to read register from modbus register but after 40100 it gives invalid register error. Where as I have the data in register even above 40100. Please help me. With this.

**Comment by rossmann-engineering** [comment]
I think that the prefix "4" in your case means that it refers to a "Holding Register" 

That means you should read Holding Register "100". Some Devices address the Modbus Registers in that way.

**Comment by Rahul828086** [comment]
Even the send it 100 it gives me error as above. anything more than 99 gives me error
