### ISSUE TITLE
Random ReadHoldingRegisters 4096 value

### ISSUE THREAD

**Issue by dnviti** [rossmann-engineering/EasyModbusTCP.NET#17]
After a short period of readings signal from plc, the value of reading goes up to 4096, instead I'm expecting only 0 and 1.

**Comment by rossmann-engineering** [comment]
Sorry I don't really understand

**Comment by dnviti** [comment]
I do not neither. Ported the software to Python, no problem.

**Comment by Padanian** [comment]
4096 is 0010 000 in binary, so actually you are receiving a 1 on the 6th bit.
It's probably a bitmapped register.
