### ISSUE TITLE
Address limitations

### ISSUE THREAD

**Issue by gabe12684351468451** [rossmann-engineering/EasyModbusTCP.NET#2]
Hi, I had problems while working with a PLC having Modbus addresses starting with 400000 (yes, that is 400k, not 40k). I figured out that the limitation comes from the ModbusClient.cs file, where the address was verified to be less than 65535. I modified all the instances to 600000, now I don't have any problems anymore. I don't know if that affects anything else, but I will see. Anyways, thought I would inform you about this, as other coders might have the same problem - I don't know if you want to implement this change in the code - your choice.

**Comment by rossmann-engineering** [comment]
Hi am very grateful about all kinds of comments and advices.

In this case I must say that the Modbus specification is very clear, that address space is limited to 65535, so this is not an issue.

In your special case, it could be:  

1: Your device doesn't correspond to the Modbus spec.
2: "4" is very often used as prefix for Holding Registers e.g. 400000 is the first Holding Registers; 400001 the second ...
