### ISSUE TITLE
Re-write serial handler

### ISSUE THREAD

**Issue by mcurry-va** [rossmann-engineering/EasyModbusTCP.NET#21]
The current serial handling is appalling, relying on timeouts, thread sleeps and other general 'bad code smell' issues.

**Comment by rossmann-engineering** [comment]
So you are complaining about the code, but were exactly is the issue?

**Comment by mcurry-va** [comment]
Issue #5 looks to be a direct relation to the issues I've mentioned.

The fix used there (synchronous calls) bypasses this code.
