### ISSUE TITLE
Is there a way to save 5 second of data from ReadHoldingRegisters ?

### ISSUE THREAD

**Issue by blarroqu** [rossmann-engineering/EasyModbusTCP.NET#27]
I try to received each data from my ModbusClient during 5 second. Actually the maximum speed I can reach is 25ms for each request of ReadHoldingRegisters. The hardware is an EM4 and have a 2ms cloack speed. Is there a way to save all values for a given time ?

**Comment by rossmann-engineering** [comment]
Sure but thats propably not a question related to the Modbus library
