### ISSUE TITLE
Modbus Client SerialPort

### ISSUE THREAD

**Issue by yueqiniu** [rossmann-engineering/EasyModbusTCP.NET#29]
I use Raspberry Pi 3B, Waveshare RS485 module connect to mainboard, RS485 module use hardware UART serial port. What is the value of serialPort in ModbusClient modbusClient = new ModbusClient ("serialPort")?

**Comment by yueqiniu** [comment]
![image](https://user-images.githubusercontent.com/5414777/62532065-3799f880-b876-11e9-8c4c-dc90689b3367.png)

**Comment by rossmann-engineering** [comment]
You have to find your serial port in the Linux console.
