### ISSUE TITLE
Slow communication from Master to slave.

### ISSUE THREAD

**Issue by nayanavv** [rossmann-engineering/EasyModbusTCP.NET#34]
Hi,

Is there any way to speed up the communication from a windows application to a Modbus client?

I have created a windows application on .Net Framework 4.5 using C# language. And used the EasyModbus TCP library for communication.
The connection stats are good, but the speed of communication is slow.
There is a two-second delay when the application sends data to the PLC and there is more than a 2-sec delay while PLC sends the data to the application.

Can anyone suggest how to increase the speed?

**Comment by rossmann-engineering** [comment]
Please see answers at Sourceforge (duplicate)
