### ISSUE TITLE
Cannot set Parity to None

### ISSUE THREAD

**Issue by darkmansad** [rossmann-engineering/EasyModbusTCP.NET#38]
Cannot set the parity to 'None' . 
If we make the following code: 

var _modbusClient=new ModbusClient();
_modbusClient.Port = 6;
_modbusClient.Parity = System.IO.Ports.Parity.None;
_modbusClient.StopBits = System.IO.Ports.StopBits.Two;
_modbusClient.Connect(); 

this code will attempt to connect with parity Even, i think this is a problem of the setter where the parity cannot be set if the 'if (serialport != null)'
If the constructor is adapted and is passed also the 'COM6' parameter the setter for  paritity parameter will work.

**Comment by Padanian** [comment]
Isn't it Port the TCP/IP port? Shouldn't it be Serialport?

**Comment by darkmansad** [comment]
> Isn't it Port the TCP/IP port? Shouldn't it be Serialport?

It's for serial port.

**Comment by Padanian** [comment]
No, it isn't.
![port](https://user-images.githubusercontent.com/7769348/85691858-2a2b6e00-b6d5-11ea-8c7d-504dd6fcce1c.png)

**Comment by Padanian** [comment]
Your example works if amended like this:

`if !_databaseTypeIsTCP{ 
//set serial data 
_modbusClient.SerialPort = "COM6"
