### ISSUE TITLE
Length should not be fixed for ReadWriteMultipleRegisters

### ISSUE THREAD

**Issue by pconfig** [rossmann-engineering/EasyModbusTCP.NET#4]
https://github.com/rossmann-engineering/EasyModbusTCP.NET/blob/61f3050c4ba38327717e075337c961e5921bf6cf/EasyModbus/ModbusClient.cs#L2592

This will make invalid modbus packages. The server module doesn't seem to check this, but other vendor's modbus implementation and wireshark do not like the incorrect length field.

(Me neither for that matter :))

**Comment by rossmann-engineering** [comment]
Should be solved with  the next version, thanks
